name: Ansible Lint
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    name: Ansible Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run ansible-lint
        uses: ansible/ansible-lint@main
        env:
          ANSIBLE_ROLES_PATH: /home/runner/work/data-plane-adoption/data-plane-adoption/tests/roles/
          ANSIBLE_LIBRARY: /home/runner/work/data-plane-adoption/data-plane-adoption/tests/plugins/modules
